apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-java-producer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-java-producer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-java-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-java-producer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "generic-java-producer.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.topic | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
